### PR TITLE
Overhaul for SILE v0.13+

### PR DESCRIPTION
**Pull request by alerque**
Update package to use SILE v0.13+'s new 3rd part package layout. This includes a rockspec so it can be installed from the repo and/or published in a way that SILE can find it.

Also updates the package itself to SILE v0.14+'s new package API and cleans up the layout a bit (which had some vertical whitespace handling issues that turned up because we fixed releated bugs upstream!).

Also if you're interested before publishing this to Lua Rocks I'd be open to moving the repo into the @sile-typesetter org (and potentially renaming the repo itself `sile-logos.sile` or `logos.sile` to go with our other naming conventions).

### CODE REVIEW

**Comment by alerque** [comment]
Feel free to migrate this to the @sile-typesetter org if you want to have it published on LuaRocks under the sile-typesetter user. There isn't any significant pros or cons though other than having access to the LuaRocks user secret all the tooling we use to automatically publish etc. should be available to other repos as well, and as far as luarocks is concerned all packages are in the root manifest, so `luarocks istalal ...` is going to find it either way. I plan on naming all of our packages as `‹package_name›.sile` in a away that will match what a document author puts in `\use[module=packages.‹package_name›]`, but there is no requirement for that. The rockspec controls what paths get installed no matter what the project is named. You can transfer or not, and if not, rename or not as you see fit.

**Comment by ctrlcctrlv** [comment]
Will do. I think I understand why you contributed this as well—this package is essentially a perfect "example package", there's really no reason it's in my account other than at the time I wrote it SILE was so immature it wasn't yet ready for something like this. :-)

**Comment by alerque** [comment]
Yes exactly! I'm working on some other packages myself (like Lilypond) that will be external too but I was having trouble coming up with a *simple* example to lead the way with the new tooling. Most of the simple things out there are also *basic* enough that it makes sense distributing them in core.

This happens to be dead simple but also a bit niche which is perfect.

**Comment by ctrlcctrlv** [comment]
@alerque Moved!

**Pull request merged**
